php_keccak.lo: /home/liuyu/Downloads/php-keccak-hash-master/php_keccak.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/liuyu/Downloads/php-keccak-hash-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/liuyu/Downloads/php-keccak-hash-master/php_keccak.c -o php_keccak.lo 
KeccakNISTInterface.lo: /home/liuyu/Downloads/php-keccak-hash-master/KeccakNISTInterface.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/liuyu/Downloads/php-keccak-hash-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/liuyu/Downloads/php-keccak-hash-master/KeccakNISTInterface.c -o KeccakNISTInterface.lo 
KeccakSponge.lo: /home/liuyu/Downloads/php-keccak-hash-master/KeccakSponge.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/liuyu/Downloads/php-keccak-hash-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/liuyu/Downloads/php-keccak-hash-master/KeccakSponge.c -o KeccakSponge.lo 
KeccakF-1600-opt64.lo: /home/liuyu/Downloads/php-keccak-hash-master/KeccakF-1600-opt64.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/liuyu/Downloads/php-keccak-hash-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/liuyu/Downloads/php-keccak-hash-master/KeccakF-1600-opt64.c -o KeccakF-1600-opt64.lo 
$(phplibdir)/keccak.la: ./keccak.la
	$(LIBTOOL) --mode=install cp ./keccak.la $(phplibdir)

./keccak.la: $(shared_objects_keccak) $(KECCAK_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_keccak) $(KECCAK_SHARED_LIBADD)

