<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/reqParamProto.proto

namespace GPBMetadata\Proto;

class ReqParamProto
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Proto\TransactionProto::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa3020a1970726f746f2f726571506172616d50726f746f2e70726f746f" .
            "22420a05506172616d12170a066d6574686f6418012001280e32072e4d45" .
            "54484f4412200a047369676e18022001280b32122e5369676e6564547261" .
            "6e73616374696f6e2ab9010a064d4554484f4412070a035041591000120b" .
            "0a07524543454956451001120f0a0b51554552595f5452414e5310021211" .
            "0a0d51554552595f42414c414e4345100312090a055452414e5310041216" .
            "0a1251554552595f5452414e535f44455441494c100512140a1051554552" .
            "595f42414c414e43455f56311006121a0a164147454e545f5041595f5245" .
            "46554e445f5155455259100712200a1c4147454e545f5041595f52454655" .
            "4e445f42415443485f51554552591008620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

