<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/transactionProto.proto

namespace GPBMetadata\Proto;

class TransactionProto
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a97020a1c70726f746f2f7472616e73616374696f6e50726f746f2e7072" .
            "6f746f22380a0b5472616e73616374696f6e120c0a0466726f6d18012001" .
            "2809120a0a02746f180220012809120f0a07636f6e74656e741803200128" .
            "0c22420a07436f6e74656e74120d0a056e6f6e6365180120012809120b0a" .
            "03676173180220012804120d0a0576616c7565180320012804120c0a0464" .
            "61746118042001280c22540a115369676e65645472616e73616374696f6e" .
            "12130a0b7472616e73616374696f6e18012001280c12110a097369676e61" .
            "7475726518022001280c12170a0663727970746f18032001280e32072e43" .
            "727970746f2a1b0a0643727970746f12080a0453454350100012070a0353" .
            "4d321001620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

