<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/transactionProto.proto

/**
 * Protobuf enum <code>Crypto</code>
 */
class Crypto
{
    /**
     * <code>SECP = 0;</code>
     */
    const SECP = 0;
    /**
     * <code>SM2 = 1;</code>
     */
    const SM2 = 1;
}

