<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/reqParamProto.proto

/**
 * Protobuf enum <code>METHOD</code>
 */
class METHOD
{
    /**
     * <code>PAY = 0;</code>
     */
    const PAY = 0;
    /**
     * <code>RECEIVE = 1;</code>
     */
    const RECEIVE = 1;
    /**
     * <code>QUERY_TRANS = 2;</code>
     */
    const QUERY_TRANS = 2;
    /**
     * <code>QUERY_BALANCE = 3;</code>
     */
    const QUERY_BALANCE = 3;
    /**
     * <code>TRANS = 4;</code>
     */
    const TRANS = 4;
    /**
     * <code>QUERY_TRANS_DETAIL = 5;</code>
     */
    const QUERY_TRANS_DETAIL = 5;
    /**
     * <code>QUERY_BALANCE_V1 = 6;</code>
     */
    const QUERY_BALANCE_V1 = 6;
    /**
     * <code>AGENT_PAY_REFUND_QUERY = 7;</code>
     */
    const AGENT_PAY_REFUND_QUERY = 7;
    /**
     * <code>AGENT_PAY_REFUND_BATCH_QUERY = 8;</code>
     */
    const AGENT_PAY_REFUND_BATCH_QUERY = 8;
}

