<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/paymentProto.proto

/**
 * Protobuf enum <code>PayInvokeMethod</code>
 */
class PayInvokeMethod
{
    /**
     * <code>PAY_REQUEST_METHOD = 0;</code>
     */
    const PAY_REQUEST_METHOD = 0;
    /**
     * <code>QUERY_METHOD = 1;</code>
     */
    const QUERY_METHOD = 1;
}

