<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/paymentProto.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>QueryAgentPayRefundParams</code>
 */
class QueryAgentPayRefundParams extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string appId = 1;</code>
     */
    private $appId = '';
    /**
     * <code>string transId = 2;</code>
     */
    private $transId = '';
    /**
     * <code>uint64 nowPage = 3;</code>
     */
    private $nowPage = 0;
    /**
     * <code>uint64 pageSize = 4;</code>
     */
    private $pageSize = 0;
    /**
     * <code>string refundDate = 5;</code>
     */
    private $refundDate = '';

    public function __construct() {
        \GPBMetadata\Proto\PaymentProto::initOnce();
        parent::__construct();
    }

    /**
     * <code>string appId = 1;</code>
     */
    public function getAppId()
    {
        return $this->appId;
    }

    /**
     * <code>string appId = 1;</code>
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->appId = $var;
    }

    /**
     * <code>string transId = 2;</code>
     */
    public function getTransId()
    {
        return $this->transId;
    }

    /**
     * <code>string transId = 2;</code>
     */
    public function setTransId($var)
    {
        GPBUtil::checkString($var, True);
        $this->transId = $var;
    }

    /**
     * <code>uint64 nowPage = 3;</code>
     */
    public function getNowPage()
    {
        return $this->nowPage;
    }

    /**
     * <code>uint64 nowPage = 3;</code>
     */
    public function setNowPage($var)
    {
        GPBUtil::checkUint64($var);
        $this->nowPage = $var;
    }

    /**
     * <code>uint64 pageSize = 4;</code>
     */
    public function getPageSize()
    {
        return $this->pageSize;
    }

    /**
     * <code>uint64 pageSize = 4;</code>
     */
    public function setPageSize($var)
    {
        GPBUtil::checkUint64($var);
        $this->pageSize = $var;
    }

    /**
     * <code>string refundDate = 5;</code>
     */
    public function getRefundDate()
    {
        return $this->refundDate;
    }

    /**
     * <code>string refundDate = 5;</code>
     */
    public function setRefundDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->refundDate = $var;
    }

}

