<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/param.proto

namespace GPBMetadata\Proto;

class Param
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5e0a1170726f746f2f706172616d2e70726f746f22170a085265715061" .
            "72616d120b0a036d736718012001280942280a1a636f6d2e697061796e6f" .
            "772e74726164652e7574696c2e64746f420a506172616d50726f746f6206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

