<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/paymentProto.proto

/**
 * Protobuf enum <code>InvokeMode</code>
 */
class InvokeMode
{
    /**
     * <code>SYNC = 0;</code>
     */
    const SYNC = 0;
    /**
     * <code>ASYNC = 1;</code>
     */
    const ASYNC = 1;
}

