<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/paymentProto.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>PayInvoke</code>
 */
class PayInvoke extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.PayInvokeMethod method = 1;</code>
     */
    private $method = 0;
    /**
     * <code>bytes params = 2;</code>
     */
    private $params = '';

    public function __construct() {
        \GPBMetadata\Proto\PaymentProto::initOnce();
        parent::__construct();
    }

    /**
     * <code>.PayInvokeMethod method = 1;</code>
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * <code>.PayInvokeMethod method = 1;</code>
     */
    public function setMethod($var)
    {
        GPBUtil::checkEnum($var, \PayInvokeMethod::class);
        $this->method = $var;
    }

    /**
     * <code>bytes params = 2;</code>
     */
    public function getParams()
    {
        return $this->params;
    }

    /**
     * <code>bytes params = 2;</code>
     */
    public function setParams($var)
    {
        GPBUtil::checkString($var, False);
        $this->params = $var;
    }

}

