<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/paymentProto.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>QueryDetailParams</code>
 */
class QueryDetailParams extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string appId = 1;</code>
     */
    private $appId = '';
    /**
     * <code>string transId = 2;</code>
     */
    private $transId = '';
    /**
     * <code>string router = 3;</code>
     */
    private $router = '';

    public function __construct() {
        \GPBMetadata\Proto\PaymentProto::initOnce();
        parent::__construct();
    }

    /**
     * <code>string appId = 1;</code>
     */
    public function getAppId()
    {
        return $this->appId;
    }

    /**
     * <code>string appId = 1;</code>
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->appId = $var;
    }

    /**
     * <code>string transId = 2;</code>
     */
    public function getTransId()
    {
        return $this->transId;
    }

    /**
     * <code>string transId = 2;</code>
     */
    public function setTransId($var)
    {
        GPBUtil::checkString($var, True);
        $this->transId = $var;
    }

    /**
     * <code>string router = 3;</code>
     */
    public function getRouter()
    {
        return $this->router;
    }

    /**
     * <code>string router = 3;</code>
     */
    public function setRouter($var)
    {
        GPBUtil::checkString($var, True);
        $this->router = $var;
    }

}

