<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/paymentProto.proto

/**
 * Protobuf enum <code>Status</code>
 */
class Status
{
    /**
     * <code>PROCESSING = 0;</code>
     */
    const PROCESSING = 0;
    /**
     * <code>SUCCESSED = 1;</code>
     */
    const SUCCESSED = 1;
    /**
     * <code>FAILED = 2;</code>
     */
    const FAILED = 2;
    /**
     * <code>ACCEPTED = 3;</code>
     */
    const ACCEPTED = 3;
}

