<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/transactionProto.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Transaction</code>
 */
class Transaction extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string from = 1;</code>
     */
    private $from = '';
    /**
     * <code>string to = 2;</code>
     */
    private $to = '';
    /**
     * <code>bytes content = 3;</code>
     */
    private $content = '';

    public function __construct() {
        \GPBMetadata\Proto\TransactionProto::initOnce();
        parent::__construct();
    }

    /**
     * <code>string from = 1;</code>
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     * <code>string from = 1;</code>
     */
    public function setFrom($var)
    {
        GPBUtil::checkString($var, True);
        $this->from = $var;
    }

    /**
     * <code>string to = 2;</code>
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * <code>string to = 2;</code>
     */
    public function setTo($var)
    {
        GPBUtil::checkString($var, True);
        $this->to = $var;
    }

    /**
     * <code>bytes content = 3;</code>
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * <code>bytes content = 3;</code>
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->content = $var;
    }

}

